version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: backend_postgres
    environment:
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: backend_password
      POSTGRES_DB: backend_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U backend_user']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    environment:
      DATABASE_URL: postgresql://backend_user:backend_password@postgres:5432/backend_db
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      NODE_ENV: development
    ports:
      - '3333:3333'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    command: npm run dev

volumes:
  postgres_data: